### ISSUE TITLE
question about luci-app-adguardhome

### ISSUE THREAD

**Issue by bonuzzz** [kongfl888/ad-rules#8]
Sorry, I couldn't find any other contacts with you and write here
Is it possible to add button to luci-app-adguardhome to switch between stable and beta versions?
to download beta version I use 
`latest_ver="$(curl --silent https://api.github.com/repos/AdguardTeam/AdGuardHome/releases | jq -r 'map(select(.prerelease)) | first | .tag_name')"`
jq package is needed here as dependency.

**Comment by kongfl888** [comment]
Done.
And you can download the ipk from [luci-app-adguardhome/releases](https://github.com/kongfl888/luci-app-adguardhome/releases)
